### ISSUE TITLE
Contamination of Pivot Table contents in Excel tables

### ISSUE THREAD

**Issue by monty79** [bizhuka/xtt#11]
When Pivot Table source is linked to a range which is filled my means of {R-...} markers. the Pivot Table contents is also modified by XTT logic 
Template:
![image](https://user-images.githubusercontent.com/26519992/176765353-2f76b26a-9f96-4f51-b446-f0f1040f7f0d.png)
As a result, the Pivot Table contents is overwritten with {R-PLTXT} logic, as in source worksheet:
![image](https://user-images.githubusercontent.com/26519992/176767610-e7f88a26-aa0a-4091-bb46-243439a4e1fb.png)

Seems that contents of XLSX components /xl/pivotTables/pivotTable*.xml should be processed, and every workbook range which is listed in`<location ref="A1:B2">` tags are supposed to be protected from change by the main replacement logic

**Comment by bizhuka** [comment]
Hi Monty
Just rename in all cells Pivot itself sheet that looks like labels {...}
You can send me the template if you have any issue

**Comment by bizhuka** [comment]
Hello 
fixed by the commit https://github.com/bizhuka/xtt/commit/5ae5340c729a158cf409f97e5c02888fbda39ba2

there is a public program with a pivot table
https://github.com/bizhuka/py_demo

**Comment by monty79** [comment]
Hello! Thank you very much for this fix!
