### ISSUE TITLE
parse excel template with error

### ISSUE THREAD

**Issue by jinzhu01** [bizhuka/xtt#15]
I meet an error when parse   excel template create  on my local PC .  I debugger  the methods,
error occurs at zcl_xtt_excel_xlsx->SHARED_STRINGS_READ()
the excel file template  shared string files like below.
"\<si\>\<t\>CHN\</t\>\<phoneticPr fontId="2" type="noConversion"/\>\</si\>"
is there some parameter can parse the data correctly?

**Comment by bizhuka** [comment]
Hi
it means that you have partial formatting within 1 cell
for example like t**hi**s  (the middle is part is bold)
is better to avoid it

in Word temlates is ok (we just receive a warning)
but in Excel we usually do need such kind of formatting

https://bizhuka.github.io/xtt/simple-structure/
![image](https://github.com/bizhuka/xtt/assets/36256417/df2dde22-3d86-498b-aa2a-3cda931445be)

if afterwards you will receive an error, please send me the template

**Comment by jinzhu01** [comment]
it  only occurs in  chinese enviroment， my sample file attached below
[aaa.xlsx](https://github.com/bizhuka/xtt/files/14645097/aaa.xlsx)
all my excel file create contain phoneticPr label

**Comment by bizhuka** [comment]
Hi
fixed in 
https://github.com/bizhuka/xtt/commit/955e37cd2d37c14bd67f566cbfcd25ca6f12891c
please update the library & let me know if there is will be an issue
