### ISSUE TITLE
Repeated call FM Z_SHOW_XTT_SCREEN

### ISSUE THREAD

**Issue by monty79** [bizhuka/xtt#4]
When file is shown in embedded window for the second time, previous PF-STATUS is not reset, so exit from program becomes impossible. 
It can be fixed in INCLUDE lz_xtt_showcli by moving SET PF-STATUS 'STATUS_100' before checking mo_cont

**Comment by bizhuka** [comment]
Sorry for late response
Thank you

fixed since https://github.com/bizhuka/xtt/commit/258f5f164f558272b66329b6564febcf254f4e44
