### ISSUE TITLE
Page break in PDF form (Nested blocks)

### ISSUE THREAD

**Issue by Evgeny2004** [bizhuka/xtt#5]
Functionality to output multiple blocks in PDF requires page break. (Example 03-03 PDF)

**Comment by bizhuka** [comment]
fixed in https://github.com/bizhuka/xtt/commit/08c4630fd0a17db9b7482a15f5dfb7ad8c057d69

for more information pls read https://github.com/bizhuka/xtt/wiki/Example-%E2%84%9603-Nested-blocks

in the end block related pdf
